# Generated by Django 4.2.2 on 2023-10-27 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
