# Generated by Django 4.2.2 on 2023-11-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_customuser_is_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
