# Generated by Django 4.2.2 on 2024-02-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='meals')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('is_diabetic', models.BooleanField(default=False)),
                ('region', models.CharField(choices=[('north', 'North'), ('south', 'South'), ('east', 'East'), ('west', 'West')], max_length=12)),
                ('gain_weight', models.BooleanField(default=False)),
                ('time', models.CharField(choices=[('breakfast', 'BreakFast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=12)),
            ],
        ),
    ]
