# Generated by Django 4.2.2 on 2024-03-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0002_alter_customuser_options_alter_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdetails',
            options={'verbose_name': 'Details', 'verbose_name_plural': 'User Details'},
        ),
        migrations.AddField(
            model_name='userdetails',
            name='diabetic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='gain_weight',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='region',
            field=models.CharField(choices=[('north', 'North'), ('south', 'South'), ('east', 'East'), ('west', 'West')], default='north', max_length=5),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='age',
            field=models.IntegerField(default=1),
        ),
    ]
