# Generated by Django 4.2.2 on 2024-03-03 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0004_remove_customuser_is_admin_alter_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='diabetic',
            new_name='is_diabetic',
        ),
    ]
